import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://keycloak.kwamekert.com/realms/skulba-realm/protocol/openid-connect/auth?client_id=skulba-app&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2F&state=ca3619c0-a281-4149-a698-7784122e534a&response_mode=fragment&response_type=code&scope=openid&nonce=72f3d9b1-bf77-4a88-a33c-0af6fefd6d31&code_challenge=OE0-EiSRCd4D37IOxsqdBU1DdoRU8NiBEIjAoqoE9Dw&code_challenge_method=S256');
  await page.getByRole('textbox', { name: 'Username or email' }).dblclick();
  await page.getByRole('textbox', { name: 'Username or email' }).fill('kraken-reset-secret');
  await page.getByRole('textbox', { name: 'Username or email' }).press('ControlOrMeta+z');
  await page.getByRole('textbox', { name: 'Username or email' }).fill('kraken-reset-secret');
  await page.getByRole('textbox', { name: 'Username or email' }).press('ControlOrMeta+z');
  await page.getByRole('textbox', { name: 'Username or email' }).fill('');
  await page.getByRole('textbox', { name: 'Username or email' }).click();
  await page.getByRole('textbox', { name: 'Username or email' }).fill('kraken@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('password');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: ' Academic Year' }).click();
  await page.getByRole('link', { name: ' Academic Year' }).click();
  await page.getByRole('link', { name: 'All Academic Years' }).click();
  await page.getByRole('link', { name: 'Add Academic Year' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('test');
  await page.getByRole('textbox').nth(1).fill('2026-04-23');
  await page.getByRole('textbox').nth(2).fill('2026-04-25');
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByText('Cancel Create').click();
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('link', { name: 'Add Academic Year' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('test');
  await page.getByRole('textbox').nth(1).fill('2026-04-17');
  await page.locator('iframe[title="chat widget"]').nth(3).contentFrame().locator('#tawk-message-preview').click();
  await page.getByRole('textbox').nth(2).fill('2026-04-24');
  await page.locator('#zpota107qof41776517259650').contentFrame().getByRole('button', { name: 'Chat widget' }).click();
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByText('Academic year with the same').click();
  await page.getByText('Academic year with the same').dblclick();
  await page.getByText('Academic year with the same').click();
  await page.getByText('Academic year with the same').click();
});